#!/usr/bin/python
import sys, pymongo
db, user = sys.argv[1:]
co = pymongo.Connection('mongodb://admin:admin@localhost')
if db in co.database_names():
  if co[db].system.users.find_one({ 'user': user }) != None:
    exit(0)
exit(1)
