#!/usr/bin/python
import os, sys, pymongo, subprocess
user    = sys.argv[1]
pwfile  = sys.argv[2] if len(sys.argv) > 2 else None
pw      = os.environ.get('PGPASS') or \
            subprocess.check_output('pwgen -s 20 1'.split()).rstrip()
co      = pymongo.Connection('mongodb://admin:admin@localhost')
co[user].add_user(user, pw)
if pwfile:
  with open(pwfile, 'a') as f:
    f.write('%s:%s\n' %(user,pw))
else:
  print('%s:%s' %(user,pw))
